# Generated by Django 5.0.3 on 2024-03-13 10:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice_Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=1000)),
                ('invoice_numb', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_numb', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('cogs', models.CharField(max_length=100)),
                ('margin', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice_Profit_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='invoice/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(max_length=1000)),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('tax', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_amount', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='sales/')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='current_stock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='amount',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='ids',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='current_stock',
            name='stock',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='current_stock_field',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
