# Generated by Django 5.0.3 on 2024-03-13 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_invoice_profit_invoice_profit_field_sales_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current_stock',
            old_name='date',
            new_name='uploaded_date',
        ),
        migrations.RenameField(
            model_name='current_stock_field',
            old_name='date',
            new_name='uploaded_date',
        ),
        migrations.RenameField(
            model_name='invoice_profit_field',
            old_name='date',
            new_name='uploaded_date',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='date',
            new_name='uploaded_date',
        ),
        migrations.RenameField(
            model_name='sales_field',
            old_name='date',
            new_name='uploaded_date',
        ),
        migrations.AddField(
            model_name='invoice_profit',
            name='uploaded_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice_profit',
            name='date',
            field=models.CharField(max_length=100),
        ),
    ]
